export const HIERARCHY = {
  PR: ["CFO", "MANAGER", "SENIOR_HR", "JUNIOR_HR"],
  TECH: ["CTO", "TRIBE_MASTER", "TEAM_LEAD", "DEVELOPER"],
};

export const DEPARTMENTS = {
  PR: ["BUSINESS_MANAGEMENT", "FINANCIAL_SERVICES"],
  TECH: ["FULL_STACK", "DATA_ENGINEER", "UI"],
};
